name: bte_regression_test_action
on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * SAT'

jobs:
  bte_regression_test_job:
    runs-on: ubuntu-latest
    services:
      bte_reasoner_api:
        image: biothings/bte_reasoner_api
        ports:
           - 3000:3000

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: test BTE API
        run: "python src/full_results.py"

      - name: Archive results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bte_regression_test_artifacts
          path: |
            output
            results

